/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 6.2.0-11ubuntu1 -O2 -fdebug-prefix-map=/build/yosys-zWLHjG/yosys-0.7=. -fstack-protector-strong -fPIC -Os) */

module ClkGeneratorEstructural(clk8f, reset_L, clk2f, clkf);
  wire _00_;
  wire _01_;
  wire _02_;
  wire [1:0] _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  output clk2f;
  input clk8f;
  output clkf;
  wire counter1;
  wire [1:0] counter2;
  input reset_L;
  NOT _18_ (
    .A(reset_L),
    .Y(_04_)
  );
  NOR _19_ (
    .A(counter2[0]),
    .B(_04_),
    .Y(_03_[0])
  );
  NOT _20_ (
    .A(counter2[0]),
    .Y(_05_)
  );
  NOT _21_ (
    .A(counter2[1]),
    .Y(_06_)
  );
  NOR _22_ (
    .A(_06_),
    .B(_05_),
    .Y(_07_)
  );
  NAND _23_ (
    .A(_06_),
    .B(_05_),
    .Y(_08_)
  );
  NAND _24_ (
    .A(_08_),
    .B(reset_L),
    .Y(_09_)
  );
  NOR _25_ (
    .A(_09_),
    .B(_07_),
    .Y(_03_[1])
  );
  NOR _26_ (
    .A(counter1),
    .B(_04_),
    .Y(_02_)
  );
  NOT _27_ (
    .A(clkf),
    .Y(_10_)
  );
  NAND _28_ (
    .A(_07_),
    .B(_10_),
    .Y(_11_)
  );
  NOR _29_ (
    .A(_07_),
    .B(_10_),
    .Y(_12_)
  );
  NOR _30_ (
    .A(_12_),
    .B(_04_),
    .Y(_13_)
  );
  NAND _31_ (
    .A(_13_),
    .B(_11_),
    .Y(_01_)
  );
  NOT _32_ (
    .A(counter1),
    .Y(_14_)
  );
  NAND _33_ (
    .A(clk2f),
    .B(_14_),
    .Y(_15_)
  );
  NOR _34_ (
    .A(clk2f),
    .B(_14_),
    .Y(_16_)
  );
  NOR _35_ (
    .A(_16_),
    .B(_04_),
    .Y(_17_)
  );
  NAND _36_ (
    .A(_17_),
    .B(_15_),
    .Y(_00_)
  );
  DFF _37_ (
    .C(clk8f),
    .D(_00_),
    .Q(clk2f)
  );
  DFF _38_ (
    .C(clk8f),
    .D(_01_),
    .Q(clkf)
  );
  DFF _39_ (
    .C(clk8f),
    .D(_02_),
    .Q(counter1)
  );
  DFF _40_ (
    .C(clk8f),
    .D(_03_[0]),
    .Q(counter2[0])
  );
  DFF _41_ (
    .C(clk8f),
    .D(_03_[1]),
    .Q(counter2[1])
  );
endmodule
