/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 6.2.0-11ubuntu1 -O2 -fdebug-prefix-map=/build/yosys-zWLHjG/yosys-0.7=. -fstack-protector-strong -fPIC -Os) */

module ParaleloSerialEstructural(clk8f, clkf, reset, reset_L, paralelo, serial);
  wire [1:0] _000_;
  wire [3:0] _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  input clk8f;
  input clkf;
  wire [1:0] counterbc;
  wire [3:0] counterdata;
  input [8:0] paralelo;
  input reset;
  input reset_L;
  output serial;
  NOT _086_ (
    .A(counterdata[0]),
    .Y(_018_)
  );
  NOT _087_ (
    .A(counterdata[3]),
    .Y(_019_)
  );
  NOT _088_ (
    .A(paralelo[8]),
    .Y(_020_)
  );
  NOR _089_ (
    .A(_020_),
    .B(reset),
    .Y(_021_)
  );
  NAND _090_ (
    .A(_021_),
    .B(_019_),
    .Y(_022_)
  );
  NOR _091_ (
    .A(_022_),
    .B(_018_),
    .Y(_023_)
  );
  NAND _092_ (
    .A(_022_),
    .B(_018_),
    .Y(_024_)
  );
  NAND _093_ (
    .A(_024_),
    .B(reset_L),
    .Y(_025_)
  );
  NOR _094_ (
    .A(_025_),
    .B(_023_),
    .Y(_001_[0])
  );
  NOR _095_ (
    .A(_023_),
    .B(counterdata[1]),
    .Y(_026_)
  );
  NAND _096_ (
    .A(_023_),
    .B(counterdata[1]),
    .Y(_027_)
  );
  NAND _097_ (
    .A(_027_),
    .B(reset_L),
    .Y(_028_)
  );
  NOR _098_ (
    .A(_028_),
    .B(_026_),
    .Y(_001_[1])
  );
  NOT _099_ (
    .A(counterdata[2]),
    .Y(_029_)
  );
  NOR _100_ (
    .A(_027_),
    .B(_029_),
    .Y(_030_)
  );
  NAND _101_ (
    .A(_027_),
    .B(_029_),
    .Y(_031_)
  );
  NAND _102_ (
    .A(_031_),
    .B(reset_L),
    .Y(_032_)
  );
  NOR _103_ (
    .A(_032_),
    .B(_030_),
    .Y(_001_[2])
  );
  NOT _104_ (
    .A(reset_L),
    .Y(_033_)
  );
  NOR _105_ (
    .A(_033_),
    .B(_019_),
    .Y(_001_[3])
  );
  NOT _106_ (
    .A(counterbc[0]),
    .Y(_034_)
  );
  NOR _107_ (
    .A(_021_),
    .B(_034_),
    .Y(_035_)
  );
  NAND _108_ (
    .A(_021_),
    .B(_034_),
    .Y(_036_)
  );
  NAND _109_ (
    .A(_036_),
    .B(reset_L),
    .Y(_037_)
  );
  NOR _110_ (
    .A(_037_),
    .B(_035_),
    .Y(_000_[0])
  );
  NAND _111_ (
    .A(_035_),
    .B(counterbc[1]),
    .Y(_038_)
  );
  NOT _112_ (
    .A(counterbc[1]),
    .Y(_039_)
  );
  NOT _113_ (
    .A(_035_),
    .Y(_040_)
  );
  NAND _114_ (
    .A(_040_),
    .B(_039_),
    .Y(_041_)
  );
  NAND _115_ (
    .A(_041_),
    .B(_038_),
    .Y(_042_)
  );
  NOR _116_ (
    .A(_042_),
    .B(_033_),
    .Y(_000_[1])
  );
  NOR _117_ (
    .A(_021_),
    .B(_039_),
    .Y(_043_)
  );
  NAND _118_ (
    .A(_019_),
    .B(_029_),
    .Y(_044_)
  );
  NOT _119_ (
    .A(counterdata[1]),
    .Y(_045_)
  );
  NAND _120_ (
    .A(_045_),
    .B(counterdata[0]),
    .Y(_046_)
  );
  NOR _121_ (
    .A(_046_),
    .B(_044_),
    .Y(_047_)
  );
  NAND _122_ (
    .A(_045_),
    .B(_018_),
    .Y(_048_)
  );
  NOR _123_ (
    .A(_048_),
    .B(_044_),
    .Y(_049_)
  );
  NOR _124_ (
    .A(_049_),
    .B(serial),
    .Y(_050_)
  );
  NOR _125_ (
    .A(counterdata[3]),
    .B(counterdata[2]),
    .Y(_051_)
  );
  NOR _126_ (
    .A(counterdata[1]),
    .B(counterdata[0]),
    .Y(_052_)
  );
  NAND _127_ (
    .A(_052_),
    .B(_051_),
    .Y(_053_)
  );
  NOR _128_ (
    .A(_053_),
    .B(paralelo[7]),
    .Y(_054_)
  );
  NOR _129_ (
    .A(_054_),
    .B(_050_),
    .Y(_055_)
  );
  NOR _130_ (
    .A(_055_),
    .B(_047_),
    .Y(_056_)
  );
  NOR _131_ (
    .A(_045_),
    .B(counterdata[0]),
    .Y(_057_)
  );
  NAND _132_ (
    .A(_057_),
    .B(_051_),
    .Y(_058_)
  );
  NOT _133_ (
    .A(paralelo[6]),
    .Y(_059_)
  );
  NAND _134_ (
    .A(_047_),
    .B(_059_),
    .Y(_060_)
  );
  NAND _135_ (
    .A(_060_),
    .B(_058_),
    .Y(_061_)
  );
  NOR _136_ (
    .A(_061_),
    .B(_056_),
    .Y(_062_)
  );
  NOR _137_ (
    .A(_045_),
    .B(_018_),
    .Y(_063_)
  );
  NOT _138_ (
    .A(_063_),
    .Y(_064_)
  );
  NOR _139_ (
    .A(_044_),
    .B(_064_),
    .Y(_065_)
  );
  NOT _140_ (
    .A(_065_),
    .Y(_066_)
  );
  NOT _141_ (
    .A(_058_),
    .Y(_067_)
  );
  NAND _142_ (
    .A(_067_),
    .B(paralelo[5]),
    .Y(_068_)
  );
  NAND _143_ (
    .A(_068_),
    .B(_066_),
    .Y(_069_)
  );
  NOR _144_ (
    .A(_069_),
    .B(_062_),
    .Y(_070_)
  );
  NOR _145_ (
    .A(counterdata[3]),
    .B(_029_),
    .Y(_071_)
  );
  NOT _146_ (
    .A(_071_),
    .Y(_072_)
  );
  NOR _147_ (
    .A(_072_),
    .B(_048_),
    .Y(_073_)
  );
  NOT _148_ (
    .A(_073_),
    .Y(_074_)
  );
  NOT _149_ (
    .A(paralelo[4]),
    .Y(_075_)
  );
  NAND _150_ (
    .A(_065_),
    .B(_075_),
    .Y(_076_)
  );
  NAND _151_ (
    .A(_076_),
    .B(_074_),
    .Y(_077_)
  );
  NOR _152_ (
    .A(_077_),
    .B(_070_),
    .Y(_078_)
  );
  NOR _153_ (
    .A(_072_),
    .B(_046_),
    .Y(_079_)
  );
  NOT _154_ (
    .A(_079_),
    .Y(_080_)
  );
  NAND _155_ (
    .A(_073_),
    .B(paralelo[3]),
    .Y(_081_)
  );
  NAND _156_ (
    .A(_081_),
    .B(_080_),
    .Y(_082_)
  );
  NOR _157_ (
    .A(_082_),
    .B(_078_),
    .Y(_083_)
  );
  NOT _158_ (
    .A(_057_),
    .Y(_084_)
  );
  NOR _159_ (
    .A(_072_),
    .B(_084_),
    .Y(_085_)
  );
  NOT _160_ (
    .A(_085_),
    .Y(_003_)
  );
  NOT _161_ (
    .A(paralelo[2]),
    .Y(_004_)
  );
  NAND _162_ (
    .A(_079_),
    .B(_004_),
    .Y(_005_)
  );
  NAND _163_ (
    .A(_005_),
    .B(_003_),
    .Y(_006_)
  );
  NOR _164_ (
    .A(_006_),
    .B(_083_),
    .Y(_007_)
  );
  NOR _165_ (
    .A(_072_),
    .B(_064_),
    .Y(_008_)
  );
  NOT _166_ (
    .A(_008_),
    .Y(_009_)
  );
  NAND _167_ (
    .A(_085_),
    .B(paralelo[1]),
    .Y(_010_)
  );
  NAND _168_ (
    .A(_010_),
    .B(_009_),
    .Y(_011_)
  );
  NOR _169_ (
    .A(_011_),
    .B(_007_),
    .Y(_012_)
  );
  NOT _170_ (
    .A(paralelo[0]),
    .Y(_013_)
  );
  NAND _171_ (
    .A(_008_),
    .B(_013_),
    .Y(_014_)
  );
  NAND _172_ (
    .A(_014_),
    .B(_021_),
    .Y(_015_)
  );
  NOR _173_ (
    .A(_015_),
    .B(_012_),
    .Y(_016_)
  );
  NOR _174_ (
    .A(_016_),
    .B(_043_),
    .Y(_017_)
  );
  NOR _175_ (
    .A(_017_),
    .B(_033_),
    .Y(_002_)
  );
  DFF _176_ (
    .C(clk8f),
    .D(_002_),
    .Q(serial)
  );
  DFF _177_ (
    .C(clk8f),
    .D(_000_[0]),
    .Q(counterbc[0])
  );
  DFF _178_ (
    .C(clk8f),
    .D(_000_[1]),
    .Q(counterbc[1])
  );
  DFF _179_ (
    .C(clk8f),
    .D(_001_[0]),
    .Q(counterdata[0])
  );
  DFF _180_ (
    .C(clk8f),
    .D(_001_[1]),
    .Q(counterdata[1])
  );
  DFF _181_ (
    .C(clk8f),
    .D(_001_[2]),
    .Q(counterdata[2])
  );
  DFF _182_ (
    .C(clk8f),
    .D(_001_[3]),
    .Q(counterdata[3])
  );
endmodule
