/* Generated by Yosys 0.8 (git sha1 5706e90) */

(* top =  1  *)
(* src = "mux.v:2" *)
module mux_synth(clk, reset_L, data_in_0, data_in_1, valid_in_0, valid_in_1, valid_out, data_out);
  (* src = "mux.v:17" *)
  wire [7:0] _000_;
  (* src = "mux.v:17" *)
  wire _001_;
  (* src = "mux.v:17" *)
  wire _002_;
  (* src = "mux.v:17" *)
  wire _003_;
  (* src = "mux.v:17" *)
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  (* src = "mux.v:3" *)
  input clk;
  (* src = "mux.v:5" *)
  input [7:0] data_in_0;
  (* src = "mux.v:6" *)
  input [7:0] data_in_1;
  (* src = "mux.v:10" *)
  output [7:0] data_out;
  (* src = "mux.v:4" *)
  input reset_L;
  (* src = "mux.v:13" *)
  wire selector;
  (* src = "mux.v:14" *)
  wire v_activo_0;
  (* src = "mux.v:15" *)
  wire v_activo_1;
  (* src = "mux.v:7" *)
  input valid_in_0;
  (* src = "mux.v:8" *)
  input valid_in_1;
  (* src = "mux.v:9" *)
  output valid_out;
  NOT _061_ (
    .A(valid_in_0),
    .Y(_007_)
  );
  NOT _062_ (
    .A(valid_in_1),
    .Y(_008_)
  );
  NOT _063_ (
    .A(v_activo_0),
    .Y(_009_)
  );
  NOT _064_ (
    .A(v_activo_1),
    .Y(_010_)
  );
  NOT _065_ (
    .A(reset_L),
    .Y(_011_)
  );
  NOT _066_ (
    .A(selector),
    .Y(_012_)
  );
  NOR _067_ (
    .A(v_activo_0),
    .B(v_activo_1),
    .Y(_013_)
  );
  NOR _068_ (
    .A(_011_),
    .B(_013_),
    .Y(_004_)
  );
  NOR _069_ (
    .A(v_activo_1),
    .B(reset_L),
    .Y(_014_)
  );
  NOR _070_ (
    .A(_007_),
    .B(v_activo_1),
    .Y(_015_)
  );
  NOR _071_ (
    .A(_008_),
    .B(v_activo_0),
    .Y(_016_)
  );
  NAND _072_ (
    .A(valid_in_1),
    .B(_009_),
    .Y(_017_)
  );
  NOR _073_ (
    .A(_015_),
    .B(_017_),
    .Y(_018_)
  );
  NOR _074_ (
    .A(_012_),
    .B(_017_),
    .Y(_019_)
  );
  NAND _075_ (
    .A(selector),
    .B(_016_),
    .Y(_020_)
  );
  NOR _076_ (
    .A(_011_),
    .B(_019_),
    .Y(_021_)
  );
  NAND _077_ (
    .A(reset_L),
    .B(_020_),
    .Y(_022_)
  );
  NOR _078_ (
    .A(_018_),
    .B(_022_),
    .Y(_023_)
  );
  NOR _079_ (
    .A(_014_),
    .B(_023_),
    .Y(_003_)
  );
  NAND _080_ (
    .A(_015_),
    .B(_021_),
    .Y(_024_)
  );
  NAND _081_ (
    .A(v_activo_0),
    .B(_011_),
    .Y(_025_)
  );
  NAND _082_ (
    .A(_024_),
    .B(_025_),
    .Y(_002_)
  );
  NAND _083_ (
    .A(_015_),
    .B(_016_),
    .Y(_026_)
  );
  NAND _084_ (
    .A(_015_),
    .B(_019_),
    .Y(_027_)
  );
  NAND _085_ (
    .A(_012_),
    .B(_026_),
    .Y(_028_)
  );
  NAND _086_ (
    .A(_027_),
    .B(_028_),
    .Y(_029_)
  );
  NOR _087_ (
    .A(_011_),
    .B(_029_),
    .Y(_001_)
  );
  NOR _088_ (
    .A(v_activo_0),
    .B(_010_),
    .Y(_030_)
  );
  NAND _089_ (
    .A(data_in_1[0]),
    .B(_030_),
    .Y(_031_)
  );
  NAND _090_ (
    .A(v_activo_0),
    .B(data_in_0[0]),
    .Y(_032_)
  );
  NAND _091_ (
    .A(_031_),
    .B(_032_),
    .Y(_033_)
  );
  NAND _092_ (
    .A(reset_L),
    .B(_033_),
    .Y(_034_)
  );
  NOT _093_ (
    .A(_034_),
    .Y(_000_[0])
  );
  NAND _094_ (
    .A(data_in_1[1]),
    .B(_030_),
    .Y(_035_)
  );
  NAND _095_ (
    .A(v_activo_0),
    .B(data_in_0[1]),
    .Y(_036_)
  );
  NAND _096_ (
    .A(_035_),
    .B(_036_),
    .Y(_037_)
  );
  NAND _097_ (
    .A(reset_L),
    .B(_037_),
    .Y(_038_)
  );
  NOT _098_ (
    .A(_038_),
    .Y(_000_[1])
  );
  NAND _099_ (
    .A(data_in_1[2]),
    .B(_030_),
    .Y(_039_)
  );
  NAND _100_ (
    .A(v_activo_0),
    .B(data_in_0[2]),
    .Y(_040_)
  );
  NAND _101_ (
    .A(_039_),
    .B(_040_),
    .Y(_041_)
  );
  NAND _102_ (
    .A(reset_L),
    .B(_041_),
    .Y(_042_)
  );
  NOT _103_ (
    .A(_042_),
    .Y(_000_[2])
  );
  NAND _104_ (
    .A(data_in_1[3]),
    .B(_030_),
    .Y(_043_)
  );
  NAND _105_ (
    .A(v_activo_0),
    .B(data_in_0[3]),
    .Y(_044_)
  );
  NAND _106_ (
    .A(_043_),
    .B(_044_),
    .Y(_045_)
  );
  NAND _107_ (
    .A(reset_L),
    .B(_045_),
    .Y(_046_)
  );
  NOT _108_ (
    .A(_046_),
    .Y(_000_[3])
  );
  NAND _109_ (
    .A(data_in_1[4]),
    .B(_030_),
    .Y(_047_)
  );
  NAND _110_ (
    .A(v_activo_0),
    .B(data_in_0[4]),
    .Y(_048_)
  );
  NAND _111_ (
    .A(_047_),
    .B(_048_),
    .Y(_049_)
  );
  NAND _112_ (
    .A(reset_L),
    .B(_049_),
    .Y(_050_)
  );
  NOT _113_ (
    .A(_050_),
    .Y(_000_[4])
  );
  NAND _114_ (
    .A(data_in_1[5]),
    .B(_030_),
    .Y(_051_)
  );
  NAND _115_ (
    .A(v_activo_0),
    .B(data_in_0[5]),
    .Y(_052_)
  );
  NAND _116_ (
    .A(_051_),
    .B(_052_),
    .Y(_053_)
  );
  NAND _117_ (
    .A(reset_L),
    .B(_053_),
    .Y(_054_)
  );
  NOT _118_ (
    .A(_054_),
    .Y(_000_[5])
  );
  NAND _119_ (
    .A(data_in_1[6]),
    .B(_030_),
    .Y(_055_)
  );
  NAND _120_ (
    .A(v_activo_0),
    .B(data_in_0[6]),
    .Y(_056_)
  );
  NAND _121_ (
    .A(_055_),
    .B(_056_),
    .Y(_057_)
  );
  NAND _122_ (
    .A(reset_L),
    .B(_057_),
    .Y(_058_)
  );
  NOT _123_ (
    .A(_058_),
    .Y(_000_[6])
  );
  NAND _124_ (
    .A(data_in_1[7]),
    .B(_030_),
    .Y(_059_)
  );
  NAND _125_ (
    .A(v_activo_0),
    .B(data_in_0[7]),
    .Y(_060_)
  );
  NAND _126_ (
    .A(_059_),
    .B(_060_),
    .Y(_005_)
  );
  NAND _127_ (
    .A(reset_L),
    .B(_005_),
    .Y(_006_)
  );
  NOT _128_ (
    .A(_006_),
    .Y(_000_[7])
  );
  (* src = "mux.v:17" *)
  DFF _129_ (
    .C(clk),
    .D(_004_),
    .Q(valid_out)
  );
  (* src = "mux.v:17" *)
  DFF _130_ (
    .C(clk),
    .D(_000_[0]),
    .Q(data_out[0])
  );
  (* src = "mux.v:17" *)
  DFF _131_ (
    .C(clk),
    .D(_000_[1]),
    .Q(data_out[1])
  );
  (* src = "mux.v:17" *)
  DFF _132_ (
    .C(clk),
    .D(_000_[2]),
    .Q(data_out[2])
  );
  (* src = "mux.v:17" *)
  DFF _133_ (
    .C(clk),
    .D(_000_[3]),
    .Q(data_out[3])
  );
  (* src = "mux.v:17" *)
  DFF _134_ (
    .C(clk),
    .D(_000_[4]),
    .Q(data_out[4])
  );
  (* src = "mux.v:17" *)
  DFF _135_ (
    .C(clk),
    .D(_000_[5]),
    .Q(data_out[5])
  );
  (* src = "mux.v:17" *)
  DFF _136_ (
    .C(clk),
    .D(_000_[6]),
    .Q(data_out[6])
  );
  (* src = "mux.v:17" *)
  DFF _137_ (
    .C(clk),
    .D(_000_[7]),
    .Q(data_out[7])
  );
  (* src = "mux.v:17" *)
  DFF _138_ (
    .C(clk),
    .D(_001_),
    .Q(selector)
  );
  (* src = "mux.v:17" *)
  DFF _139_ (
    .C(clk),
    .D(_002_),
    .Q(v_activo_0)
  );
  (* src = "mux.v:17" *)
  DFF _140_ (
    .C(clk),
    .D(_003_),
    .Q(v_activo_1)
  );
endmodule
